# Generated by Django 5.0.7 on 2024-08-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('cmn_qst_no', models.AutoField(primary_key=True, serialize=False)),
                ('cmn_qst_txt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('item_photo', models.ImageField(blank=True, upload_to='shop_items/')),
                ('item_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_exp', models.IntegerField(default=0)),
                ('tree_skin', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tree_start_date', models.DateField()),
                ('item_list', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('wrt_strg', models.IntegerField()),
                ('cmn_qst_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.commonquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CommonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('rgst_time', models.DateTimeField()),
                ('cmn_qst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.commonquestion')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.family')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('feed_img', models.ImageField(blank=True, upload_to='feeds/')),
                ('feed_txt', models.TextField()),
                ('feed_rgst_dt', models.DateField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.family')),
            ],
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('rgst_time', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_start_dt', models.DateField()),
                ('tree_end_dt', models.DateField()),
                ('first_feed_id', models.IntegerField(blank=True, null=True)),
                ('second_feed_id', models.IntegerField(blank=True, null=True)),
                ('third_feed_id', models.IntegerField(blank=True, null=True)),
                ('tree_skin', models.CharField(max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.family')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalQuestion',
            fields=[
                ('prsn_qst_no', models.AutoField(primary_key=True, serialize=False)),
                ('prsn_qst_txt', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.family')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('rgst_time', models.DateTimeField()),
                ('cmt_txt', models.TextField()),
                ('prsn_qst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.personalquestion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('kakao_token', models.CharField(max_length=300)),
                ('lst_cmn_qst_no', models.IntegerField()),
                ('liked_cmn_qst_no', models.CharField(default='', max_length=255)),
                ('liked_psn_qst_no', models.CharField(default='', max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.family')),
            ],
        ),
    ]
