# Generated by Django 5.0.7 on 2024-08-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_cmn_qst_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_psn_qst_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
