# Generated by Django 4.2.14 on 2024-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='first_feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='second_feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='third_feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
