# Generated by Django 4.2.14 on 2024-08-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_alter_commoncomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.user'),
        ),
    ]
