# Generated by Django 4.2.14 on 2024-08-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_family_first_feed_id_family_second_feed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='wrt_strg',
            field=models.IntegerField(default=0),
        ),
    ]
