# Generated by Django 4.2.14 on 2024-08-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_alter_feedcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='cmt_txt',
            field=models.TextField(default=''),
        ),
    ]
