# Generated by Django 4.2.14 on 2024-08-04 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_feedcomment_cmt_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='first_feed_id',
        ),
        migrations.RemoveField(
            model_name='family',
            name='second_feed_id',
        ),
        migrations.RemoveField(
            model_name='family',
            name='third_feed_id',
        ),
        migrations.AddField(
            model_name='family',
            name='first_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_feed', to='memory.feed'),
        ),
        migrations.AddField(
            model_name='family',
            name='second_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_feed', to='memory.feed'),
        ),
        migrations.AddField(
            model_name='family',
            name='third_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_feed', to='memory.feed'),
        ),
    ]
